### ISSUE TITLE
ConnectDbs Form Does Not Allow Linking to Big Rivers Backend

### ISSUE THREAD

**Issue by hmthomas** [NCPN/big_rivers_app#1] opened 2017-11-18 19:01 UTC
The application is currently set up with the backend file connection location set to C:\NCPN_Databases\Big_Rivers. There does not appear to be a way to easily change this. There is no option to change the backend link on the ConnectDbs form (it only allows the master species database location to be changed). For data entry in the office, users should be able to link to the backend on X. If this option is not available on the ConnectDbs form, users will need to be trained to use the Access Linked Table Manager (including reopening the frontend using Shift).

**Comment by NCPN** [comment] 2017-11-24 20:16
By design, ConnectDbs draws the linked databases listed from tsys_Link_Dbs which should include records for _**both**_ Master Species & the Big Rivers back-end.

To display both Master species & the back-end a record for the back-end must exist in this table.

If no record exists for the back-end in tsys_Link_Dbs, it will not be available to change in ConnectDbs.

Closing issue as a data issue.  _See also issue #21_

**Closed by NCPN** 2017-11-24 20:16 UTC
Labels: enhancement
